//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by LDtkToUnity
//     from Assets/Levels/overworld_village/overworld_village.ldtk
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/// <summary>
/// LDtk Enum for overworld_village
/// </summary>
public enum Enemy_bush
{
    ENEMY_ONE,
    ENEMY_TWO,
    ENEMY_THREE
}